{{ $ns              :=  "mas-uninstall-pipelines" }}
{{ $role_name       :=  "mas-undeploy-role" }}
{{ $secret_name     :=  "mas-undeploy-secret" }}
{{ $crole_name      :=  "mas-undeploy-crole" }}
{{ $sa_name         :=  "mas-undeploy-sa" }}
{{ $scc_name        :=  "mas-undeploy-scc" }}
{{ $rb_name         :=  "mas-undeploy-rb" }}
{{ $crb_name        :=  "mas-undeploy-crb" }}
{{ $job_name        :=  "mas-undeploy-job" }}
{{ $readonly_root_filesystem        :=  printf "%s" .Values.readonly_root_filesystem }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secret_name }}
  namespace: {{ $ns }}
data:
  entitlement_key: {{ .Values.mas_entitlement_key }}
  authorized_entitlement: {{ .Values.mas_license }}
type: Opaque

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa_name }}
  namespace: {{ $ns }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $crb_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ $sa_name }}
  namespace: {{ $ns }}


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $job_name }}
  generateName: "{{ $job_name }}-"
  namespace: {{ $ns }}
  annotations:
  #  checkov.io/skip1: CKV_K8S_20
  #  checkov.io/skip2: CKV_K8S_37

    checkov.io/skip3: CKV_K8S_40
    checkov.io/skip4: CKV_K8S_35
    checkov.io/skip6: CKV_K8S_38
    checkov.io/skip12: CKV_K8S_31
    checkov.io/skip16: CKV_K8S_22

  #  checkov.io/skip5: CKV_K8S_43
  #  checkov.io/skip10: CKV_K8S_29


  #  checkov.io/skip7: CKV_K8S_13
  #  checkov.io/skip8: CKV_K8S_11
  #  checkov.io/skip9: CKV_K8S_10

  #  checkov.io/skip11: CKV_K8S_28

  #  checkov.io/skip13: CKV_K8S_30
  #  checkov.io/skip14: CKV_K8S_12
  #  checkov.io/skip15: CKV_K8S_23


spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: {{ $job_name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ $sa_name }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ $job_name }}
          # 8.0.0-pre.master - sha256:5b5222caecdd860840fd1eb070999e29ed356310474741f76934d0a9f8921d99
          # below sha is for quay.io/ibmmas/cli:8.0.0-pre.mascore-2054 (tag 8.0.0), update it once we get a new release tag
          image: quay.io/ibmmas/cli:8.0.2-pre.master
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: {{ $readonly_root_filesystem }}
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          command:
            - /bin/sh
            - -c
            - |

              set -e

              export ENTITLEMENT_KEY=$(cat /etc/mas/deploy/secrets/entitlement_key)
              export AUTHORIZED_ENTITLEMENT=$(cat /etc/mas/deploy/secrets/authorized_entitlement)
              ##echo "ENTITLEMENT_KEY=${ENTITLEMENT_KEY}"
              ##echo "AUTHORIZED_ENTITLEMENT=${AUTHORIZED_ENTITLEMENT}"
              SLS_LICENSE_FILE_LOCAL=/etc/mas/deploy/secrets/authorized_entitlement
              ##echo "------authorized_entitlement.lic--------------"
              ##cat $SLS_LICENSE_FILE_LOCAL
              ##echo "------authorized_entitlement.lic--------------"

              echo "MAS_INSTANCE_ID=${MAS_INSTANCE_ID}"
              echo "MAS_WORKSPACE_ID${MAS_WORKSPACE_ID}"
              echo "MAS_WORKSPACE_NAME=${MAS_WORKSPACE_NAME}"
              echo "MAS_CATALOG_VERSION=${MAS_CATALOG_VERSION}"
              echo "MAS_CHANNEL=${MAS_CHANNEL}"
              echo "SLS_LICENSE_ID=${SLS_LICENSE_ID}"
              ##echo "SLS_LICENSE_FILE_LOCAL=${SLS_LICENSE_FILE_LOCAL}"
              echo "UDS_CONTACT_EMAIL=${UDS_CONTACT_EMAIL}"
              echo "UDS_CONTACT_FIRSTNAME=${UDS_CONTACT_FIRSTNAME}"
              echo "UDS_CONTACT_LASTNAME=${UDS_CONTACT_LASTNAME}"
              echo "STORAGE_CLASS_RWX=${STORAGE_CLASS_RWX}"
              echo "PIPELINE_STORAGE_CLASS=${PIPELINE_STORAGE_CLASS}"
              echo "PIPELINE_STORAGE_ACCESSMODE=${PIPELINE_STORAGE_ACCESSMODE}"
              echo "MANAGE_CHANNEL=${MANAGE_CHANNEL}"
              echo "MANAGE_JDBC_CONFIG_SCOPE=${MANAGE_JDBC_CONFIG_SCOPE}"
              echo "MANAGE_COMPONENTS=${MANAGE_COMPONENTS}"
              echo "DB2U_CHANNEL=${DB2U_CHANNEL}"
              echo "DB2U_CPU_REQUEST=${DB2U_CPU_REQUEST}"
              echo "DB2U_CPU_LIMIT=${DB2U_CPU_LIMIT}"
              echo "DB2U_MEMORY_REQUEST=${DB2U_MEMORY_REQUEST}"
              echo "DB2U_MEMORY_LIMIT=${DB2U_MEMORY_LIMIT}"
              echo "DB2U_BACKUP_STORAGE=${DB2U_BACKUP_STORAGE}"
              echo "DB2U_DATA_STORAGE=${DB2U_DATA_STORAGE}"
              echo "DB2U_LOGS_STORAGE=${DB2U_LOGS_STORAGE}"
              echo "DB2U_META_STORAGE=${DB2U_META_STORAGE}"
              echo "DB2U_TEMP_STORAGE=${DB2U_TEMP_STORAGE}"

              echo "DEPLOYMENT_FLAVOUR=${DEPLOYMENT_FLAVOUR}"
              DEPLOYMENT_FLAVOUR=${DEPLOYMENT_FLAVOUR:-"core"}

              if [ "${DEPLOYMENT_FLAVOUR}" == "core" ]; then
              echo "Inside helm pre-delete hook and uninstalling MAS Core instance"
              varstr=$(oc get namespaces | grep mas-"${MAS_INSTANCE_ID}"-core | awk -F' ' '{print $2}')
              if [[ $varstr == "Active"  ]]; then
              echo "MAS instance namespace found"
              mas uninstall -i "${MAS_INSTANCE_ID}" --no-confirm
              for (( i=0; i<=15; i++ ));
              do
              varstr2=$(oc get pr -n mas-${MAS_INSTANCE_ID}-pipelines | grep uninstall | awk -F' ' '{print $3}')
              if [[ $varstr2 == "Completed"  ]]; then
              echo "Uninstall pipeline has completed successfully"
              break
              elif [[ $varstr2 == "Running"  ]]; then
              echo "Uninstall pipeline is still running"
              sleep 120
              elif [[ $varstr2 == "Failed"  ]]; then
              echo "Uninstall pipeline has failed"
              exit
              else
              echo "Other error condition"
              exit
              fi
              done
              else
              echo "No MAS instance namespace found due to a failed installation"
              fi
              elif [ "${DEPLOYMENT_FLAVOUR}" == "manage" ]; then
              echo "Inside helm pre-delete hook and uninstalling MAS Core + Manage instance"
              varstr=$(oc get namespaces | grep mas-"${MAS_INSTANCE_ID}"-core | awk -F' ' '{print $2}')
              if [[ $varstr == "Active"  ]]; then
              echo "MAS instance namespace found"
              mas uninstall -i "${MAS_INSTANCE_ID}" --no-confirm
              for (( i=0; i<=15; i++ ));
              do
              varstr2=$(oc get pr -n mas-${MAS_INSTANCE_ID}-pipelines | grep uninstall | awk -F' ' '{print $3}')
              if [[ $varstr2 == "Completed"  ]]; then
              echo "Uninstall pipeline has completed successfully"
              break
              elif [[ $varstr2 == "Running"  ]]; then
              echo "Uninstall pipeline is still running"
              sleep 120
              elif [[ $varstr2 == "Failed"  ]]; then
              echo "Uninstall pipeline has failed"
              exit
              else
              echo "Other error condition"
              exit
              fi
              oc delete project db2u
              sleep 600
              done
              else
              echo "No MAS instance namespace found due to a failed installation"
              fi
              fi

          env:
            - name: MAS_INSTANCE_ID
              value: "{{ .Values.mas_instance_id }}"

            - name: MAS_WORKSPACE_ID
              value: "{{ .Values.mas_workspace_id }}"
            - name: MAS_WORKSPACE_NAME
              value: "{{ .Values.mas_workspace_name }}"
            - name: MAS_CATALOG_VERSION
              value: "{{ .Values.mas_catalog_version }}"
            - name: MAS_CHANNEL
              value: "{{ .Values.mas_channel }}"

            - name: SLS_LICENSE_ID
              value: "{{ .Values.sls_license_id }}"
            - name: UDS_CONTACT_EMAIL
              value: "{{ .Values.uds_contact_email }}"
            - name: UDS_CONTACT_FIRSTNAME
              value: "{{ .Values.uds_contact_firstname }}"
            - name: UDS_CONTACT_LASTNAME
              value: "{{ .Values.uds_contact_lastname }}"
            - name: STORAGE_CLASS_RWO
              value: "{{ .Values.storage_class_rwo }}"
            - name: STORAGE_CLASS_RWX
              value: "{{ .Values.storage_class_rwx }}"
            - name: PIPELINE_STORAGE_CLASS
              value: "{{ .Values.pipeline_storage_class }}"
            - name: PIPELINE_STORAGE_ACCESSMODE
              value: "{{ .Values.pipeline_storage_accessmode }}"

            # Manage specific
            - name: MANAGE_CHANNEL
              value: "{{ .Values.manage_channel }}"
            - name: MANAGE_JDBC_CONFIG_SCOPE
              value: "{{ .Values.manage_jdbc_config_scope }}"
            - name: MANAGE_COMPONENTS
              value: "{{ .Values.manage_components }}"
            - name: DB2U_CHANNEL
              value: "{{ .Values.db2u_channel }}"
            - name: DB2U_CPU_REQUEST
              value: "{{ .Values.db2u_cpu_request }}"
            - name: DB2U_CPU_LIMIT
              value: "{{ .Values.db2u_cpu_limit }}"
            - name: DB2U_MEMORY_REQUEST
              value: "{{ .Values.db2u_memory_request }}"
            - name: DB2U_MEMORY_LIMIT
              value: "{{ .Values.db2u_memory_limit }}"
            - name: DB2U_BACKUP_STORAGE
              value: "{{ .Values.db2u_backup_storage }}"
            - name: DB2U_DATA_STORAGE
              value: "{{ .Values.db2u_data_storage }}"
            - name: DB2U_LOGS_STORAGE
              value: "{{ .Values.db2u_logs_storage }}"
            - name: DB2U_META_STORAGE
              value: "{{ .Values.db2u_meta_storage }}"
            - name: DB2U_TEMP_STORAGE
              value: "{{ .Values.db2u_temp_storage }}"
            - name: DEPLOYMENT_FLAVOUR
              value: "{{ .Values.deployment_flavour }}"

            - name: ENTITLEMENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: entitlement_key

            - name: AUTHORIZED_ENTITLEMENT
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: authorized_entitlement

          volumeMounts:
            - name: {{ $secret_name }}
              readOnly: true
              mountPath: /etc/mas/deploy/secrets
            #- mountPath: /opt/app-root/src
            #  name: app-root-volume

      volumes:
        - name: {{ $secret_name }}
          secret:
            secretName: {{ $secret_name }}
            defaultMode: 420
            optional: false
        #- name: app-root-volume
        #  emptyDir: {}

  backoffLimit: 6
