---
mas_instance_id:
mas_workspace_id:
mas_workspace_name:
mas_catalog_version: v9-240730-amd64
mas_channel: 9.0.x
sls_license_id: replace
contact_email:
contact_firstname:
contact_lastname:
storage_class_rwo: ibmc-vpc-block-retain-10iops-tier
storage_class_rwx:
pipeline_storage_class: ibmc-vpc-block-retain-10iops-tier
pipeline_storage_accessmode: ReadWriteOnce
entitlement_key:
mas_license: replace
deployment_flavor:

# manage specific
manage_channel: 9.0.x
manage_jdbc_config_scope: workspace-application
manage_components: "base=latest,health=latest"
db2_channel: "v110509.0"
db2_cpu_request: 6000m
db2_cpu_limit: 8000m
db2_memory_request: 10Gi
db2_memory_limit: 14Gi
db2_backup_storage: 100Gi
db2_data_storage: 120Gi
db2_logs_storage: 100Gi
db2_meta_storage: 20Gi
db2_temp_storage: 100Gi
readonly_root_filesystem: "false"